## =============================================================================
## HLA allele associations in cognitively healthy centenarians (CHC):
## comparison with literature effect sizes (UK Biobank, AD-GWAS, SARS-CoV-2)
##
## This script:
##   1. Loads regression results from the 100-plus Study (CHC vs. middle-aged
##      controls) and combines them with published effect sizes for the same
##      HLA alleles from three external sources:
##        - UK Biobank PheWAS (Butler-Laporte et al., 2024)
##        - Alzheimer's disease GWAS (Bellenguez et al., 2022)
##        - SARS-CoV-2 susceptibility (Augusto et al., 2021)
##   2. Computes a "Centenarian Effect Ratio" (CER) for each allele-trait pair:
##      the ratio of the (reversed-sign) CHC effect to the literature disease
##      effect, with bootstrapped confidence intervals and p-values.
##   3. Applies multiple testing correction (FDR).
##   4. Produces Figures 2-6 and Supplementary Figure 1, plus Supplementary
##      Tables 1-2 and Table 1.
##
## NOTE: Figure 1 is not generated by this script - it was created separately
## and is not based on the data processed here.
## =============================================================================

library(readxl)
library(tidyr)
library(dplyr)
library(ggplot2)
library(corrplot)

set.seed(1515)  # Fixed seed for reproducibility of the bootstrap-based CER calculation

setwd("/path/to/repository/root")  # update to the local path of the repository root


## -----------------------------------------------------------------------------
## Helper functions
## -----------------------------------------------------------------------------

# Computes the "Centenarian Effect Ratio" (CER) for a single allele-trait row.
# The CER is defined as: -beta_CHC / beta_literature
# (the minus sign converts the CHC effect, originally on the "becoming a CHC"
#  scale, to the same direction as the disease-risk effect in the literature).
#
# Confidence intervals and a two-tailed p-value are obtained by Monte Carlo
# simulation: both the CHC beta and the literature effect are sampled from
# normal distributions defined by their reported estimate and standard error,
# and the ratio of these draws is used to build an empirical distribution.
#
# Input: a single row (named vector / data.frame row) containing:
#   - beta, standard_error  : effect estimate and SE from the 100-plus Study
#   - effect, error.beta    : effect estimate and SE from the literature source
# Output: numeric vector c(ratioLCI, ratioUCI, one_tail_p, two_tail_p)
process_row_ctr_cent_new <- function(row) {
  numerator <- rnorm(n = 1e4, mean = -as.numeric(row["beta"]), sd = as.numeric(row["standard_error"])) # 100-plus
  denominator <- rnorm(n = 1e4, mean = as.numeric(row["effect"]), sd = as.numeric(row["error.beta"])) # Literature
  tmp_ratios <- numerator / denominator
  ratioLCI <- quantile(tmp_ratios, .025)[[1]]
  ratioUCI <- quantile(tmp_ratios, .975)[[1]]
  cdf <- ecdf(tmp_ratios)
  cdf2 <- cdf(0) # proportion of simulated ratios below zero
  if (cdf2 > 0.5) {
    one_tail_p <- 1 - cdf2
    two_tail_p <- one_tail_p * 2
  } else {
    one_tail_p <- cdf2
    two_tail_p <- one_tail_p * 2
  }
  # Return a numeric vector of the calculated values
  return(c(ratioLCI, ratioUCI, one_tail_p, two_tail_p))
}


## -----------------------------------------------------------------------------
## 1. Load input data
## -----------------------------------------------------------------------------

# HLA loci for which imputation is reliable (used to filter UKB associations
# and to label/order alleles by locus throughout the script)
imputable_loci <- c("A", "C", "B", "DRB1", "DQA1", "DQB1", "DPB1")

# Main regression results: HLA allele associations with CHC status (and
# sex-corrected versions), from the 100-plus Study
all_regression <- read.csv2("inputs/regression_npj_aging_2025.csv")
colnames(all_regression)[colnames(all_regression) == "odds_ratio"] <- "ors"
colnames(all_regression)[colnames(all_regression) == "freq_total"] <- "freq_all"

# UK Biobank PheWAS summary statistics (Butler-Laporte et al., 2024)
# Sheet 20 contains HLA allele-disease associations
ukbb_disease <- read_xlsx("inputs/BUTLER-LAPORTE_2024.xlsx", sheet = 20)

# Alzheimer's disease GWAS summary statistics (Bellenguez et al., 2022)
# Sheet 2 contains the relevant HLA allele associations
ad_lit <- read_excel("inputs/AD_GWAS_2022.xlsx", sheet = 2)
ad_lit <- separate(ad_lit, CI, into = c("l95", "u95"), sep = "-")  # split "lower-upper" 95% CI string
ad_lit$P <- as.numeric(gsub(" x 10", "e", ad_lit$P))               # convert "x 10^-n" notation to numeric
ad_lit$l95 <- as.numeric(ad_lit$l95)
ad_lit$effect <- log(ad_lit$OR)                                    # convert OR to log-odds (beta) scale
ad_lit$error.or <- (ad_lit$OR - ad_lit$l95) / 1.96                 # SE on the OR scale from the 95% CI
ad_lit$error.beta <- ad_lit$error.or / ad_lit$OR                   # approximate SE on the log-odds scale


## -----------------------------------------------------------------------------
## 2. Centenarians-controls vs. AD-GWAS literature effects
## -----------------------------------------------------------------------------

# Merge CHC association results (cent_ctr_original model) with AD-GWAS
# literature effects on matching alleles
cent_ctr_adlit <- merge(ad_lit, all_regression[which(all_regression$association == "cent_ctr_original"), ], by.x = "Allele", by.y = "allele")
cent_ctr_adlit$ratio <- -cent_ctr_adlit$beta / cent_ctr_adlit$effect

# Compute CER (ratio) confidence intervals and p-values per allele
new_columns <- t(sapply(split(cent_ctr_adlit, seq(nrow(cent_ctr_adlit))), process_row_ctr_cent_new))
colnames(new_columns) <- c("ratioLCI", "ratioUCI", "one_tail_p", "two_tail_p")
cent_ctr_adlit <- cbind(cent_ctr_adlit, new_columns)


## -----------------------------------------------------------------------------
## 3. UK Biobank associations: filtering and merging
## -----------------------------------------------------------------------------

# Select UKB associations meeting the significance threshold specified in the
# UKB paper: European ancestry, two-field allele resolution, Bonferroni-style
# threshold (5e-8 / 11 traits)
ukbb_tomerge <- ukbb_disease[which(ukbb_disease$Ancestry == "eur" & ukbb_disease$Pvalue < 0.00000005 / 11 &
                                     ukbb_disease$Type == "two_fields_allele"), ]

# Merge UKB-significant alleles with our CHC association results
ukbb_centctr <- merge(ukbb_tomerge, all_regression[which(all_regression$association == "cent_ctr_original"), ], by.x = "Marker", by.y = "allele")

# Filter out alleles with frequency < 1% (these would not reach the power
# threshold for significance and are excluded from downstream analysis)
ukbb_centctr <- subset(ukbb_centctr, freq_all > 0.01)


## -----------------------------------------------------------------------------
## 4. Compute Centenarian Effect Ratios for UKB-derived associations
## -----------------------------------------------------------------------------

# Standardise UKB literature effect column names to match process_row_ctr_cent_new()
colnames(ukbb_centctr)[colnames(ukbb_centctr) == "Beta"] <- "effect"
colnames(ukbb_centctr)[colnames(ukbb_centctr) == "SE"] <- "error.beta"
ukbb_centctr$ratio <- -ukbb_centctr$beta / ukbb_centctr$effect

# Compute CER confidence intervals and p-values per allele-trait pair
new_columns <- t(sapply(split(ukbb_centctr, seq(nrow(ukbb_centctr))), process_row_ctr_cent_new))
colnames(new_columns) <- c("ratioLCI", "ratioUCI", "one_tail_p", "two_tail_p")
ukbb_centctr <- cbind(ukbb_centctr, new_columns)

# Create a combined allele-trait identifier used for plotting and merging
ukbb_centctr <- ukbb_centctr %>%
  mutate(marker_trait = paste(Marker, Trait, sep = "_"))


## -----------------------------------------------------------------------------
## 5. Combine UKB-derived and AD-GWAS-derived associations into one data frame
## -----------------------------------------------------------------------------

# Select and harmonise columns from the UKB-based results
ukbb_centctr_ad <- ukbb_centctr %>%
  select(Marker, Trait, ratio, marker_trait, ratioLCI, ratioUCI, two_tail_p, effect, error.beta, beta, standard_error, p_value, freq_cases, freq_controls, freq_all, Allele_frequency, Pvalue, ors, lower_ci, upper_ci)

# Select and harmonise columns from the AD-GWAS-based results, renaming to
# match the UKB column names so the two data frames can be row-bound
ad_centad_toukb <- cent_ctr_adlit %>%
  select(Allele, ratio, ratioLCI, ratioUCI, two_tail_p, effect, error.beta, beta, standard_error, p_value, freq_cases, freq_controls, freq_all, Freq, P, ors, lower_ci, upper_ci)
colnames(ad_centad_toukb)[colnames(ad_centad_toukb) == "Allele"] <- "Marker"
colnames(ad_centad_toukb)[colnames(ad_centad_toukb) == "Freq"] <- "Allele_frequency"
colnames(ad_centad_toukb)[colnames(ad_centad_toukb) == "P"] <- "p_lit"
colnames(ukbb_centctr_ad)[colnames(ukbb_centctr_ad) == "Pvalue"] <- "p_lit"

# Tag AD-GWAS-derived rows with Trait = "AD" and build the matching identifier
ad_centad_toukb$Trait <- "AD"
ad_centad_toukb <- ad_centad_toukb %>%
  mutate(marker_trait = paste(Marker, Trait, sep = "_"))

ukbb_centctr_ad <- rbind(ukbb_centctr_ad, ad_centad_toukb)


## -----------------------------------------------------------------------------
## 6. Add SARS-CoV-2 association (Augusto et al., 2021)
## -----------------------------------------------------------------------------

# Manually define the published HLA-B*15:01 / SARS-CoV-2 association
# (asymptomatic vs. symptomatic infection, Augusto et al. 2021)
covid <- data.frame(
  Marker = "B*15:01",
  Trait = "Covid",
  marker_trait = "B*15:01_Covid",
  or = 2.38,
  orLCI = 1.51,
  orUCI = 3.65,
  p_lit = 3e-5,
  Freq_asymp = 0.1103,
  Freq_symp = 0.0495,
  Allele_frequency = NA,
  effect = NA,
  error.beta = NA
)
covid$error.beta <- (log(covid$orUCI) - log(covid$orLCI)) / (2 * 1.96) # SE on log-odds scale from 95% CI
covid$effect <- log(covid$or)                                          # convert OR to log-odds (beta)
covid$Allele_frequency <- covid$Freq_asymp + covid$Freq_symp           # combined allele frequency

# Merge the COVID literature effect with the corresponding CHC association
covid_cent_ctr <- merge(covid, all_regression[which(all_regression$association == "cent_ctr_original"), ], by.x = "Marker", by.y = "allele")

# Calculate CER, confidence intervals and p-value for B*15:01 / COVID
covid_cent_ctr$ratio <- -covid_cent_ctr$beta / covid_cent_ctr$effect
new_columns <- t(sapply(split(covid_cent_ctr, seq(nrow(covid_cent_ctr))), process_row_ctr_cent_new))
colnames(new_columns) <- c("ratioLCI", "ratioUCI", "one_tail_p", "two_tail_p")
covid_cent_ctr <- cbind(covid_cent_ctr, new_columns)

# Select and harmonise columns, then add to the combined data frame
covid_cent_ctr_torbind <- covid_cent_ctr %>%
  select(Marker, Trait, ratio, marker_trait, ratioLCI, ratioUCI, two_tail_p, effect, error.beta, beta, standard_error, p_value, freq_cases, freq_controls, freq_all, Allele_frequency, p_lit, ors, lower_ci, upper_ci)

ukbb_centctr_ad <- rbind(ukbb_centctr_ad, covid_cent_ctr_torbind)


## -----------------------------------------------------------------------------
## 7. Multiple testing correction
## -----------------------------------------------------------------------------

# FDR-correct the CHC association p-values (cent_ctr_original model),
# restricted to alleles with freq > 1% that are present in the combined
# allele-trait data frame
all_regression_corrected <- all_regression %>% subset(association == "cent_ctr_original" &
                                                                  freq_all > 0.01 &
                                                                  allele %in% ukbb_centctr_ad$Marker)
p_values <- all_regression_corrected$p_value
p_values_fdr <- p.adjust(p_values, method = "fdr")
length(p_values_fdr[which(p_values_fdr < 0.1)]) # check: 6 alleles significant at FDR < 0.1 (Table 1)
all_regression_corrected$p_corrected <- p_values_fdr

# Attach the FDR-corrected allele-level p-value to each allele-trait row
ukbb_centctr_ad <- merge(ukbb_centctr_ad, all_regression_corrected[, c("allele", "p_corrected")], by.x = "Marker", by.y = "allele", all.y = FALSE)

# FDR-correct the CER (ratio) two-tailed p-values across all allele-trait pairs
p_values <- ukbb_centctr_ad$two_tail_p
p_values_fdr <- p.adjust(p_values, method = "fdr")
length(p_values_fdr[which(p_values_fdr < 0.1)]) # check: 21 allele-disease associations significant at FDR < 0.1 (Figure 4)
ukbb_centctr_ad$two_tail_p_fdr <- p_values_fdr

# ukbb_centctr_ad is now the final combined data frame used for plotting and tables


## -----------------------------------------------------------------------------
## 8. Figure 5: Centenarian Effect Ratio (CER) per allele-trait pair
## -----------------------------------------------------------------------------

# Reorder the 'Trait' factor levels by frequency, with AD forced to appear first
trait_counts <- table(ukbb_centctr_ad$Trait)
trait_counts["AD"] <- 1000000 # Artificially make AD the one with the highest counts to show first in the plot
ukbb_centctr_ad$Trait <- factor(ukbb_centctr_ad$Trait, levels = names(sort(trait_counts, decreasing = TRUE)))

# Recode internal trait codes to display abbreviations
ukbb_centctr_ad <- ukbb_centctr_ad %>%
  mutate(Trait_recoded = recode(Trait,
                                "ms_demyelinating" = "MS",
                                "psoriasis" = "Psoriasis",
                                "coeliac" = "CD",
                                "AD" = "AD",
                                "pmr_gca" = "PMR-GCA",
                                "t1d" = "T1D",
                                "asthma" = "Asthma",
                                "ankylosing_spondylitis" = "AS",
                                "auto_immune_thyroid_disorders" = "ATD",
                                "Covid" = "SARS-CoV-2",
                                "ulcerative_colitis" = "UC",
                                "rheumatoid_arthritis" = "RA"))

# Named vector mapping each marker_trait combination to its allele label,
# used for x-axis tick labels in the faceted plots below
labels_for_x <- setNames(ukbb_centctr_ad$Marker, ukbb_centctr_ad$marker_trait)

# Plot: CER per allele, faceted by trait, with FDR significance markers
p <- ggplot(ukbb_centctr_ad, aes(x = reorder(marker_trait, -ratio), y = ratio, color = Trait_recoded)) +
  geom_point(size = 1.5) +
  geom_errorbar(aes(ymin = ratioLCI, ymax = ratioUCI), alpha = 0.25, show.legend = FALSE) +
  geom_text(aes(label = ifelse(two_tail_p_fdr < 0.1, "*", "")), color = "red", size = 3, vjust = 0.2, show.legend = FALSE) +
  geom_hline(yintercept = c(0), linetype = "solid", size = 0.2, color = "black") +
  scale_color_manual(values = c("black", "#66C2A5", "#FC8D62", "#8DA0CB", "#E78AC3", "#A6D854", "#FFD92F", "#E5C494", "#B3B3B3", "#1F78B4", "#33A02C", "#6A3D9A")) +
  scale_y_continuous(breaks = c(-6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 10, 15)) +
  coord_cartesian(ylim = c(-6, 15)) +
  labs(
    x = "",
    y = "Centenarian Effect Ratio (CER)"
  ) +
  facet_grid(. ~ Trait_recoded, scales = "free", space = "free", switch = "x") +
  theme_minimal() +
  theme(
    text = element_text(size = 14),
    axis.text.x = element_blank(),  # Removes x-axis text
    axis.ticks.x = element_blank(), # Removes x-axis ticks
    panel.grid.major.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    strip.text.x = element_text(size = 10),  # Facet labels angled
    panel.spacing = unit(0, "lines"),  # Remove spacing between panels
    panel.border = element_rect(color = "black", fill = NA, size = 0.2),  # Add border between grids
    plot.margin = margin(t = 5, r = 5, b = 0, l = 5)  # Reduce bottom margin
  ) +
  scale_x_discrete(labels = labels_for_x[levels(reorder(ukbb_centctr_ad$marker_trait, -ukbb_centctr_ad$ratio))]) +
  guides(color = "none")  # Remove legend

ggsave("figures/figure5_raw.pdf", plot = p,
       width = 170 / 25.4,  # 170 mm to inches
       height = 128 / 25.4, # 128 mm to inches, 4:3
       dpi = 300,         # 300 dpi resolution
       device = "pdf")


## -----------------------------------------------------------------------------
## 9. Supplementary Figure 1: literature ORs per allele-trait pair
## -----------------------------------------------------------------------------

# Derive literature OR and its 95% CI from the literature beta/SE, plus a
# per-trait flag for the lowest literature p-value (annotated in the plot)
ukbb_centctr_ad <- ukbb_centctr_ad %>%
  mutate(
    ors_lit = exp(effect),
    ors_lit_LCI = ors_lit - 1.96 * ors_lit * error.beta,
    ors_lit_UCI = ors_lit + 1.96 * ors_lit * error.beta
  )
ukbb_centctr_ad <- ukbb_centctr_ad %>%
  group_by(Trait) %>%
  mutate(min_pvalue = ifelse(p_lit == min(p_lit), "+", "")) %>%
  ungroup()

# Plot: literature OR per allele (excluding COVID), faceted by trait, with
# FDR significance markers (from the allele-level CHC association)
p <- ggplot(ukbb_centctr_ad[which(ukbb_centctr_ad$Trait != "Covid"), ], aes(x = reorder(marker_trait, -ratio), y = ors_lit, color = Trait_recoded)) +
  geom_point(size = 1.5) +
  geom_errorbar(aes(ymin = ors_lit_UCI, ymax = ors_lit_LCI), alpha = 0.25, show.legend = FALSE) +
  geom_text(aes(label = min_pvalue), color = "red", size = 3, vjust = -0.5, show.legend = FALSE) +
  geom_text(aes(label = ifelse(p_corrected < 0.1, "*", "")), color = "red", size = 3, vjust = 0.2, show.legend = FALSE) +
  geom_hline(yintercept = c(1), linetype = "solid", size = 0.2, color = "black") +
  scale_color_manual(values = c("black", "#66C2A5", "#FC8D62", "#8DA0CB", "#E78AC3", "#A6D854", "#FFD92F", "#E5C494", "#B3B3B3", "#1F78B4", "#33A02C")) +
  scale_y_log10(breaks = c(0.25, 0.5, 0.75, 1, 1.5, 2, 3, 6)) +
  coord_cartesian(ylim = c(0.25, 7.0)) +
  labs(
    x = "",
    y = "OR of disease in literature"
  ) +
  facet_grid(. ~ Trait_recoded, scales = "free", space = "free", switch = "x") +
  theme_minimal() +
  theme(
    text = element_text(size = 14),
    axis.text.x = element_blank(),  # Makes the x-axis text smaller and diagonal
    panel.grid.major.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    strip.text.x = element_text(size = 10),  # smaller text size and vertical orientation
    panel.spacing = unit(0, "lines"),  # Remove spacing between panels
    panel.border = element_rect(color = "black", fill = NA, size = 0.2)  # Add border between grids
  ) +
  scale_x_discrete(labels = labels_for_x[levels(reorder(ukbb_centctr_ad$marker_trait, -ukbb_centctr_ad$ratio))]) +
  guides(color = "none")  # Remove legend

ggsave("figures/suppfigure1_raw.pdf", plot = p,
       width = 170 / 25.4,  # 170 mm to inches
       height = 128 / 25.4, # 128 mm to inches, 4:3
       dpi = 300,         # 300 dpi resolution
       device = "pdf")


## -----------------------------------------------------------------------------
## 10. Figure 2: allele frequencies (CHC vs. middle-aged controls) by locus
## -----------------------------------------------------------------------------

# Extract the HLA locus (e.g. "A", "DRB1") from the allele name and order it
# according to the imputable_loci vector
ukbb_centctr_ad <- ukbb_centctr_ad %>%
  mutate(Locus = sub("\\*.*", "", Marker))  # Extracts Locus from Marker
ukbb_centctr_ad$Locus <- factor(ukbb_centctr_ad$Locus, levels = imputable_loci) # sort loci
gene_names <- c("A" = "HLA-A", "B" = "HLA-B", "C" = "HLA-C", "DPB1" = "HLA-DPB1", "DQA1" = "HLA-DQA1", "DQB1" = "HLA-DQB1", "DRB1" = "HLA-DRB1")

# Dumbbell-style plot: frequency in middle-aged controls vs. CHC for each
# allele, faceted vertically by HLA locus, with allele-level FDR significance
# markers
p_alt_flipped <- ggplot(distinct(ukbb_centctr_ad, Marker, .keep_all = TRUE),
                        aes(y = reorder(Marker, -freq_all))) +
  # horizontal reference lines
  geom_hline(yintercept = seq(0.5,
                              length(unique(reorder(ukbb_centctr_ad$Marker, -ukbb_centctr_ad$freq_all))) + 0.5,
                              by = 1),
             color = "#E0E0E0", size = 0.2) +

  # connect case-control points
  geom_segment(aes(y = reorder(Marker, -freq_all), yend = reorder(Marker, -freq_all),
                   x = freq_cases, xend = freq_controls),
               color = "grey", size = 0.5) +
  # points
  geom_point(aes(x = freq_cases, shape = "Middle-aged\nhealthy\nindividuals", color = "Middle-aged\nhealthy\nindividuals"), size = 2) +
  geom_point(aes(x = freq_controls, shape = "Cognitively\nHealthy\nCentenarians\n", color = "Cognitively\nHealthy\nCentenarians\n"), size = 2) +
  # large "*" for significance
  geom_text(
    aes(
      x = 0.405,
      label = ifelse(!is.na(p_corrected) & p_corrected < 0.1, "*", "")
    ),
    color = "red", size = 5, hjust = 0, vjust = 0.7, show.legend = FALSE
  ) +
  # smaller marker text next to the "*"
  geom_text(
    aes(
      x = 0.42,  # slightly offset to the right
      label = ifelse(!is.na(p_corrected) & p_corrected < 0.1, Marker, "")
    ),
    color = "red", size = 3, hjust = 0, vjust = 0.5, show.legend = FALSE
  ) +
  # shapes and colors
  scale_shape_manual(values = c("Middle-aged\nhealthy\nindividuals" = 16, "Cognitively\nHealthy\nCentenarians\n" = 17)) +
  scale_color_manual(values = c("Middle-aged\nhealthy\nindividuals" = "darkblue", "Cognitively\nHealthy\nCentenarians\n" = "orange")) +

  # x axis
  scale_x_continuous(limits = c(0, 0.55), expand = c(0, 0)) +
  labs(y = "", x = "Allele frequency") +

  # facets (vertical by locus)
  facet_grid(Locus ~ ., scales = "free_y", space = "free", labeller = as_labeller(gene_names)) +

  theme_minimal() +
  theme(
    text = element_text(size = 14),
    axis.text.y = element_text(size = 7),   # larger, clearer allele names
    axis.title.x = element_text(size = 12),
    strip.text.y = element_text(size = 8, angle = 0),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.spacing = unit(1, "lines"),
    legend.text = element_text(size = 8)#,
    #plot.margin = margin(5, 50, 5, 10)   # extra right margin for red labels
  ) +
  guides(color = guide_legend(title = ""), shape = guide_legend(title = ""))

# Save in standard figure size for journal (approx 170 mm x 170 mm)
ggsave("figures/figure2_raw.pdf",
       plot = p_alt_flipped,
       width = 170 / 25.4,   # ~170 mm
       height = 170 / 25.4,  # ~170 mm
       dpi = 300,
       device = "pdf")


## -----------------------------------------------------------------------------
## 11. Figure 4: corrplot of CER for FDR-significant alleles, by trait
## -----------------------------------------------------------------------------

# Identify alleles reaching FDR < 0.1 for the CER (allele-trait level), then
# keep all trait associations for those alleles
significant_marker_traits <- subset(ukbb_centctr_ad, two_tail_p_fdr < 0.1)
significant <- subset(ukbb_centctr_ad, Marker %in% significant_marker_traits$Marker)

# Set a fixed display order for the significant alleles
custom_order <- c("A*02:01", "C*03:04", "B*40:01", "DRB1*01:01", "DQA1*01:01", "DQB1*05:01")
significant$Marker <- factor(significant$Marker, levels = custom_order)

# Create the full grid of allele x trait combinations (so missing
# combinations appear as NA in the matrix rather than being dropped)
significant_combinations <- expand.grid(
  Marker = unique(significant$Marker),
  Trait = unique(significant$Trait)
)
significant_combinations <- significant_combinations %>%
  left_join(significant, by = c("Marker", "Trait")) %>%
  group_by(Marker, Trait)

# Build the CER (ratio) matrix: rows = traits, columns = alleles
ratio_matrix <- significant_combinations %>%
  summarise(ratio) %>%
  ungroup() %>%
  pivot_wider(names_from = Marker, values_from = ratio) %>%
  as.data.frame()
rownames(ratio_matrix) <- ratio_matrix$Trait
ratio_matrix$Trait <- NULL
ratio_matrix <- as.matrix(ratio_matrix)

# Manually set trait labels (matching the order produced above)
rownames(ratio_matrix) <- c("AD", "ATD", "CD", "Psoriasis", "Asthma", "T1D", "PMR-GCA", "AS", "MS")
new_order <- c("AD", "CD", "Asthma", "ATD", "AS", "PMR-GCA", "Psoriasis", "T1D", "MS")
ratio_matrix <- ratio_matrix[new_order, ]
# Reorder again to the final display order used in the figure
new_order <- c("AD", "AS", "PMR-GCA", "T1D", "Asthma", "ATD", "MS", "CD", "Psoriasis")
ratio_matrix <- ratio_matrix[new_order, ]
rownames(ratio_matrix) <- c("Alzheimer's Disease (AD)", "Ankylosing Spondylitis (AS)", "Polymialgia Rheumatica or\nGiant Cell Arteritis (PMR-GCA)", "Type 1 Diabetes (T1D)",
                             "Asthma", "Autoimmune Thyroid\nDisorders (ATD)", "Multiple Sclerosis (MS)", "Celiac Disease (CD)", "Psoriasis")

pdf("figures/figure4_raw.pdf", width = 170 / 25.4, height = 128 / 25.4)
corrplot(ratio_matrix, method = "circle", is.corr = FALSE,
         col.lim = c(-8, 12), col = rev(COL2('RdBu', 190)),
         tl.col = "black", tl.cex = 0.8, tl.srt = 70,
         na.label = "x", na.label.col = "gray90")
dev.off()
# Note: column (allele) names are added manually to the figure afterwards


## -----------------------------------------------------------------------------
## 12. Table 1: summary table of FDR-significant allele-trait associations
## -----------------------------------------------------------------------------

significant_subset <- significant[, c("Marker", "ors", "lower_ci", "upper_ci",
                                      "freq_controls", "freq_cases", "p_value",
                                      "p_corrected", "Trait", "ratio", "ratioLCI",
                                      "ratioUCI", "ors_lit", "ors_lit_LCI", "ors_lit_UCI")]

# Transform CHC ORs to represent the odds of becoming a CHC (rather than the
# odds of NOT becoming a CHC, as originally coded), by inverting OR and CI
significant_subset <- significant_subset %>%
  mutate(ors = 1 / ors, lower_ci = 1 / lower_ci, upper_ci = 1 / upper_ci)

# Round p-values to 3 decimals
significant_subset[, "p_value"] <- round(significant_subset[, "p_value"], 3)
significant_subset[, "p_corrected"] <- round(significant_subset[, "p_corrected"], 3)

# Round all other numeric columns to 2 decimals
numeric_cols <- sapply(significant_subset, is.numeric)  # Identify numeric columns
numeric_cols <- names(significant_subset)[numeric_cols] # Get column names of numeric columns
numeric_cols <- setdiff(numeric_cols, c("p_value", "p_corrected")) # exclude p-value columns from this rounding
significant_subset[, numeric_cols] <- round(significant_subset[, numeric_cols], 2)

# Combine OR and its 95% CI into a single display string: "OR [upper-lower]"
# (note: order is reversed because "-" cannot otherwise be parsed unambiguously
#  for negative values)
significant_subset$ORs_CI <- paste0(significant_subset$ors, " [",
                                    significant_subset$upper_ci, "-", # bc it's reserved, reverse order for lower and upper
                                    significant_subset$lower_ci, "]")

# Combine CER and its 95% CI into a single display string
significant_subset$CER_CI <- paste0(significant_subset$ratio, " [",
                                    significant_subset$ratioLCI, " - ",
                                    significant_subset$ratioUCI, "]")

# Combine literature OR and its 95% CI into a single display string
significant_subset$ORs_lit_CI <- paste0(significant_subset$ors_lit, " [",
                                    significant_subset$ors_lit_LCI, " - ",
                                    significant_subset$ors_lit_UCI, "]")

# Recode internal trait codes to display abbreviations
significant_subset <- significant_subset %>%
  mutate(Trait = recode(Trait,
                          "ms_demyelinating" = "MS",
                          "psoriasis" = "Psoriasis",
                          "coeliac" = "CD",
                          "AD" = "AD",
                          "pmr_gca" = "PMR-GCA",
                          "t1d" = "T1D",
                          "asthma" = "Asthma",
                          "ankylosing_spondylitis" = "AS",
                          "auto_immune_thyroid_disorders" = "ATD"))

# Select and rename final columns for the table
significant_subset <- significant_subset[, c("Marker", "ORs_CI", "freq_controls",
                                             "freq_cases", "p_value", "p_corrected",
                                             "Trait", "CER_CI", "ORs_lit_CI")]
colnames(significant_subset) <- c("Allele", "ORs CHCs [CIs]", "Freq. CHC", "Freq. Controls", "p-value", "FDR", "Disease", "CER [CIs]", "ORs disease [CIs]")

# Write Table 1 as a tab-separated text file
write.table(significant_subset, file = "tables/table1.txt", sep = "\t", row.names = FALSE, quote = FALSE)


## -----------------------------------------------------------------------------
## 13. Figure 3: Linkage disequilibrium (LD) matrix for the significant alleles
## -----------------------------------------------------------------------------

# Load pairwise LD (r2) matrix and corresponding allele/SNP identifiers
r2 <- data.table::fread('inputs/hla.ld', h = F)
bim <- data.table::fread('inputs/hla.bim', h = F)
allele_names <- bim$V2  # Assuming the SNP names are in the second column
r2 <- as.matrix(r2)
rownames(r2) <- allele_names
colnames(r2) <- allele_names

# Subset the LD matrix to the 6 alleles that were significant for CHC depletion
custom_order <- c("A*02:01", "C*03:04", "B*40:01", "DRB1*01:01", "DQA1*01:01", "DQB1*05:01")
r2_significant <- r2[(custom_order), (custom_order)]
r2_significant[r2_significant == 1] <- NA  # mask self-pairs (perfect LD)

# Color scale for LD heatmap
ld_colors <- c("#313695", "#74ADD1", "#4DAC26", "#FDAE61", "#D73027")  # Dark blue, light blue, light green, orange, red
color_breaks <- c(0, 0.2, 0.4, 0.6, 0.8, 1)  # Breakpoints for colors
col_fun <- colorRampPalette(ld_colors)

pdf("figures/figure3_raw.pdf", width = 170 / 25.4, height = 128 / 25.4)
corrplot(r2_significant, method = 'color', type = 'upper', is.corr = FALSE,
         col = col_fun(length(color_breaks) - 1), tl.col = "black", addgrid.col = "white", #tl.srt=45,
         na.label = " ", na.label.col = "gray90", col.lim = c(0, 1),
         addCoef.col = "black",     # Add text labels
         number.cex = 0.6,          # Adjust text size
         number.digits = 2)
dev.off()


## -----------------------------------------------------------------------------
## 14. Figure 6: literature effects across AD-associated and FDR-significant alleles
## -----------------------------------------------------------------------------

# Combine alleles associated with AD with the FDR-significant alleles from
# Figure 4 (pleiotropy comparison set)
ad_marker_traits <- subset(ukbb_centctr_ad, Trait == "AD")
ad_pleio <- subset(ukbb_centctr_ad, Marker %in% ad_marker_traits$Marker | Marker %in% significant_marker_traits$Marker)

# Customize order of alleles
custom_order <- c("A*02:01", "C*03:04", "B*40:01", "DRB1*01:01", "DQA1*01:01", "DQB1*05:01", "B*57:01", "DRB1*04:04", "DQA1*03:01", "DQB1*03:02")
ad_pleio$Marker <- factor(ad_pleio$Marker, levels = custom_order)

# Create the full grid of allele x trait combinations
ad_pleio_combinations <- expand.grid(
  Marker = unique(ad_pleio$Marker),
  Trait = unique(ad_pleio$Trait)
)

ad_pleio_combinations <- ad_pleio_combinations %>%
  left_join(ad_pleio, by = c("Marker", "Trait")) %>%
  group_by(Marker, Trait)

# Build the literature effect (beta) matrix: rows = traits, columns = alleles
# - this is the matrix used for Figure 6
effect_matrix_ad <- ad_pleio_combinations %>%
  summarise(effect) %>%
  ungroup() %>%
  pivot_wider(names_from = Marker, values_from = effect) %>%
  as.data.frame()
rownames(effect_matrix_ad) <- effect_matrix_ad$Trait
effect_matrix_ad$Trait <- NULL
effect_matrix_ad <- as.matrix(effect_matrix_ad)
# Manually set trait labels, see order above
rownames(effect_matrix_ad) <- c("Alzheimer's Disease (AD)", "Autoimmune Thyroid\nDisorders (ATD)",
                                 "Celiac Disease (CD)", "Psoriasis", "Asthma", "Rheumatoid Arthritis (RA)", "Type 1 Diabetes (T1D)",
                                 "Polymialgia Rheumatica or\nGiant Cell Arteritis (PMR-GCA)", "Ankylosing Spondylitis (AS)",
                                 "Multiple Sclerosis (MS)", "Ulcerative Colitis (UC)")
new_order <- c("Alzheimer's Disease (AD)", "Ankylosing Spondylitis (AS)", "Polymialgia Rheumatica or\nGiant Cell Arteritis (PMR-GCA)",
              "Type 1 Diabetes (T1D)", "Asthma", "Autoimmune Thyroid\nDisorders (ATD)", "Multiple Sclerosis (MS)",
              "Celiac Disease (CD)", "Psoriasis", "Rheumatoid Arthritis (RA)", "Ulcerative Colitis (UC)")
effect_matrix_ad <- effect_matrix_ad[new_order, ]

# Build the CHC effect (beta) matrix: rows = traits, columns = alleles
beta_matrix_ad <- ad_pleio_combinations %>%
  summarise(beta) %>%
  ungroup() %>%
  pivot_wider(names_from = Marker, values_from = beta) %>%
  as.data.frame()
rownames(beta_matrix_ad) <- beta_matrix_ad$Trait
beta_matrix_ad$Trait <- NULL
beta_matrix_ad <- as.matrix(beta_matrix_ad)
# Manually set trait labels, see order above
rownames(beta_matrix_ad) <- c("Alzheimer's Disease (AD)", "Autoimmune Thyroid\nDisorders (ATD)",
                               "Celiac Disease (CD)", "Psoriasis", "Asthma", "Rheumatoid Arthritis (RA)", "Type 1 Diabetes (T1D)",
                               "Polymialgia Rheumatica or\nGiant Cell Arteritis (PMR-GCA)", "Ankylosing Spondylitis (AS)",
                               "Multiple Sclerosis (MS)", "Ulcerative Colitis (UC)")
new_order <- c("Alzheimer's Disease (AD)", "Ankylosing Spondylitis (AS)", "Polymialgia Rheumatica or\nGiant Cell Arteritis (PMR-GCA)",
              "Type 1 Diabetes (T1D)", "Asthma", "Autoimmune Thyroid\nDisorders (ATD)", "Multiple Sclerosis (MS)",
              "Celiac Disease (CD)", "Psoriasis", "Rheumatoid Arthritis (RA)", "Ulcerative Colitis (UC)")
beta_matrix_ad <- beta_matrix_ad[new_order, ]

# Combine the per-trait CHC betas into a single "Cognitively Healthy
# Centenarian (CHC)" row (first non-NA value per allele across traits),
# sign-flipped to align with the literature effect direction
beta_matrix_combined_ad <- apply(beta_matrix_ad, 2, function(col) col[which(!is.na(col))[1]])
beta_matrix_combined_ad <- matrix(beta_matrix_combined_ad, nrow = 1)
rownames(beta_matrix_combined_ad) <- "Cognitively Healthy\nCentenarian (CHC)"
beta_matrix_combined_ad <- -beta_matrix_combined_ad

# Append the CHC row to the literature-effect matrix and reorder columns
# according to custom_order (10 alleles total)
effect_matrix_ad_extended <- rbind(effect_matrix_ad, beta_matrix_combined_ad)
rownames(effect_matrix_ad_extended) <- c(rownames(effect_matrix_ad), "Cognitively Healthy\nCentenarian (CHC)")
effect_matrix_ad_extended <- effect_matrix_ad_extended[, custom_order]

pdf("figures/figure6.pdf", width = 170 / 25.4, height = 128 / 25.4)
corrplot(effect_matrix_ad_extended, method = "circle", is.corr = FALSE,
         col = rev(COL2('RdBu', 200)), col.lim = c(-1.2, 1.2), tl.col = "black", tl.cex = 0.8, tl.srt = 70,
         na.label = "x", na.label.col = "gray90")
dev.off()


## -----------------------------------------------------------------------------
## 15. Supplementary Table 1: full allele-trait association table
## -----------------------------------------------------------------------------

supptable1 <- ukbb_centctr_ad[, c("Marker", "freq_all", "freq_controls", "freq_cases",
                                  "ors", "lower_ci", "upper_ci",  "p_value",
                                      "p_corrected", "Trait", "ratio", "ratioLCI",
                                      "ratioUCI", "two_tail_p", "two_tail_p_fdr", "Allele_frequency",
                                  "ors_lit", "ors_lit_LCI", "ors_lit_UCI", "p_lit")]

# Recode internal trait codes to display abbreviations (including SARS-CoV-2)
supptable1 <- supptable1 %>%
  mutate(Trait = recode(Trait,
                        "ms_demyelinating" = "MS",
                        "psoriasis" = "Psoriasis",
                        "coeliac" = "CD",
                        "AD" = "AD",
                        "pmr_gca" = "PMR-GCA",
                        "t1d" = "T1D",
                        "asthma" = "Asthma",
                        "ankylosing_spondylitis" = "AS",
                        "auto_immune_thyroid_disorders" = "ATD",
                        "covid" = "SARS-CoV-2",
                        "rheumatoid_arthritis" = "RA",
                        "ulcerative_colitis" = "UC"))

colnames(supptable1) <- c("Allele", "Freq.study", "Freq. Controls", "Freq. CHCs", "OR CHCs", "OR_CHC_LowerCI", "OR_CHC_UpperCI",
                          "p-value_CHC", "FDR_CHC", "Disease", "CER", "CER_lowerCI", "CER_upperCI", "p-value_CER", "FDR_CER", "Freq.literature",
                          "OR_literature", "OR_literature_LowerCI", "OR_literature_UpperCI", "p-value_literature")

# Write Supplementary Table 1
write.csv2(supptable1, file = "tables/supptable1.csv", row.names = FALSE, quote = FALSE)


## -----------------------------------------------------------------------------
## 16. Supplementary Table 2: sex-corrected CHC associations (rebuttal analysis)
## -----------------------------------------------------------------------------

# Reload the regression input and the freshly written Supplementary Table 1
# (re-reading ensures supptable1 reflects the file as written to disk)
all_regression <- read.csv2("inputs/regression_npj_aging_2025.csv")
supptable1 <- read.csv2("tables/supptable1.csv")

# For the alleles included in Supplementary Table 1, extract the sex-corrected
# CHC association results and apply FDR correction
supptable2 <- all_regression %>% subset(association == "cent_ctr_sex_covariate" & allele %in% unique(supptable1$Allele))

p_values_2 <- supptable2$p_value
p_values_fdr_2 <- p.adjust(p_values_2, method = "fdr")
supptable2$p_corrected <- p_values_fdr_2

# Select and rename final columns for the table
supptable2 <- supptable2 %>% select(allele, freq_total, freq_controls, freq_cases, odds_ratio, lower_ci, upper_ci, p_value, p_corrected)
colnames(supptable2) <- c("Allele", "Freq.study", "Freq. Controls", "Freq. CHCs", "OR CHCs", "OR_CHC_LowerCI", "OR_CHC_UpperCI",
                          "p-value_CHC", "FDR_CHC")

# Write Supplementary Table 2
write.csv2(supptable2, "tables/supptable2.csv", row.names = FALSE, quote = FALSE)
